const tagList=[
    {
        mid:0,
        name:'年龄分级',
        description:'这是对于宁这个年龄应有的分级',
        pmid:0,
        count:0
    },
    {
        mid:1,
        name:'类型分级',
        description:'这是对于这个文章应有的分级',
        pmid:0,
        count:0
    },
    {
        mid:2,
        name:'健全',
        description:'适合18岁以上宝宝阅读',
        pmid:0,
        count:0
    },
    {
        mid:3,
        name:'超级健全',
        description:'适合0岁以上宝宝阅读',
        pmid:0,
        count:0
    },
    {
        mid:4,
        name:'剧情',
        description:'阅读一下剧情吧',
        pmid:1,
        count:0
    },
    {
        mid:5,
        name:'科技',
        description:'植物种植',
        pmid:1,
        count:0
    }
]
export default tagList
